// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA6R9ocjLgczFvRv6f0IKIEqu9GEDgz2M',
    appId: '1:668985675708:web:33457b65d45e455e5c65b9',
    messagingSenderId: '668985675708',
    projectId: 'mylafapp',
    authDomain: 'mylafapp.firebaseapp.com',
    storageBucket: 'mylafapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPcDwyUqZG70zeUh5VpY1Gp-nMlDUelK4',
    appId: '1:668985675708:android:45f7537a32acfff15c65b9',
    messagingSenderId: '668985675708',
    projectId: 'mylafapp',
    storageBucket: 'mylafapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGtMkhaYmpwWPbesSU5qtBiigPTlRKeN0',
    appId: '1:668985675708:ios:0ad135c9bdc76e735c65b9',
    messagingSenderId: '668985675708',
    projectId: 'mylafapp',
    storageBucket: 'mylafapp.firebasestorage.app',
    iosBundleId: 'com.example.letsfind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGtMkhaYmpwWPbesSU5qtBiigPTlRKeN0',
    appId: '1:668985675708:ios:0ad135c9bdc76e735c65b9',
    messagingSenderId: '668985675708',
    projectId: 'mylafapp',
    storageBucket: 'mylafapp.firebasestorage.app',
    iosBundleId: 'com.example.letsfind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA6R9ocjLgczFvRv6f0IKIEqu9GEDgz2M',
    appId: '1:668985675708:web:f86f55fa3a64bf715c65b9',
    messagingSenderId: '668985675708',
    projectId: 'mylafapp',
    authDomain: 'mylafapp.firebaseapp.com',
    storageBucket: 'mylafapp.firebasestorage.app',
  );
}
